### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by EricDriussi** [antonk52/markdowny.nvim#2]
Hi there!

I think it would be cool to have an option to disable the default keybindings (or not setting them at all).
They can conflict with other keybindings the user might have.

It could also be nice if the functions (bold, italics and link) worked in normal mode as well.
They would ideally grab the current word under cursor and simply process that element just like the visual selection is currently processed.

Great work on the plugin!

**Comment by antonk52** [comment]
Thanks for the suggestions.

> an option to disable the default keybindings

To "disable" default keymaps you can not call the setup function as all it does is sets the default keymaps.

> It could also be nice if the functions (bold, italics and link) worked in normal mode as well.

I do like the idea of normal mode mappings and it is easy to implement. One issue that I do not have a work around for is that <kbd>ctrl</kbd><kbd>i</kbd> or `<C-i>` actually sends `<Tab>` signal in most terminal emulators. I have not seen anyone map tab key in visual mode and that's why I thought it was okay in the visual mode. In normal mode most people have this use <Tab> to expand snippets and/or navigate a completion menu. I would not want this plugin to conflict with it. Thus I did not add this functionality.

**Comment by begabba** [comment]
Great work!
I would also expect the plugin to work in linewise-visual mode. Both for single and multiple selected lines.

**Comment by antonk52** [comment]
> I would also expect the plugin to work in linewise-visual mode. Both for single and multiple selected lines.

This sounds reasonable. Would you like to send a PR?

**Comment by antonk52** [comment]
V-Line support was added in #3
